version: '3'
services:
  nifi:
    image: apache/nifi:1.8.0
    container_name: nifi
    ports:
      - "8080:8080"
    volumes:
      - nifi:/opt/nifi
      - ./extra_lib:/opt/nifi/nifi_current/libs

volumes:
  nifi: